packages:
  - apps/*
  - packages/*

catalog:
  prettier: ^3.6.1
  typescript: ^5.8.3
  eslint-plugin-turbo: 2.9.3
  '@sentry/nextjs': ^10.47.0
  oxlint: ^1.58.0

catalogMode: prefer

onlyBuiltDependencies:
  - '@sentry/cli'
  - bufferutil
  - esbuild
  - msw
  - sharp
  - utf-8-validate
