name: Run Checks

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  run-all-checks:
    name: Run All Checks
    runs-on: ubuntu-latest-16-core
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup pnpm 10.6.5
        uses: pnpm/action-setup@v4
        with:
          version: 10.6.5

      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install Dependencies
        run: pnpm i

      - name: Run Checks
        run: pnpm check

      - name: Install Playwright
        run: pnpx playwright install --with-deps chromium

      - name: Run End-to-End Tests
        run: pnpm test:e2e
        shell: bash
