name: Run Checks

on:
  pull_request:
  push:
    branches:
      - main

env:
  NEXT_PUBLIC_APTOS_DEVNET_API_KEY: ${{ secrets.NEXT_PUBLIC_APTOS_DEVNET_API_KEY }}
  NEXT_PUBLIC_MULTISIG_INDEXER_MAINNET_API_KEY: ${{ secrets.NEXT_PUBLIC_MULTISIG_INDEXER_MAINNET_API_KEY }}

jobs:
  run-all-checks:
    name: Run All Checks
    runs-on: ubuntu-latest-16-core
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install Dependencies
        run: pnpm i

      - name: Run Checks
        run: pnpm check

      - name: Install Playwright
        run: cd apps/web && pnpm exec playwright install

      - name: Run End-to-End Tests
        run: pnpm test:e2e
        shell: bash
