name: Run Checks

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

env:
  NEXT_PUBLIC_APTOS_DEVNET_API_KEY: ${{ secrets.NEXT_PUBLIC_APTOS_DEVNET_API_KEY }}
  NEXT_PUBLIC_MULTISIG_INDEXER_MAINNET_API_KEY: ${{ secrets.NEXT_PUBLIC_MULTISIG_INDEXER_MAINNET_API_KEY }}
  APTOS_DEVNET_FAUCET_AUTH_TOKEN: ${{ secrets.APTOS_DEVNET_FAUCET_AUTH_TOKEN }}

jobs:
  run-all-checks:
    name: Run All Checks
    runs-on: ubuntu-latest-16-core
    steps:
      - name: Checkout Repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

      - name: Setup Node.js 22.x
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 22.x

      - name: Install safe-chain
        run: curl -fsSL https://github.com/AikidoSec/safe-chain/releases/download/1.4.7/install-safe-chain.sh | sh -s -- --ci

      - name: Install Dependencies
        run: pnpm i

      - name: Run Checks
        run: pnpm check

      - name: Install Playwright
        run: cd apps/web && pnpm exec playwright install

      - name: Run End-to-End Tests
        run: pnpm test:e2e
        shell: bash
