name: Run Checks

on:
  pull_request:
  push:
    branches:
      - main

env:
  NEXT_PUBLIC_APTOS_DEVNET_API_KEY: ${{ secrets.NEXT_PUBLIC_APTOS_DEVNET_API_KEY }}
  NEXT_PUBLIC_MULTISIG_INDEXER_MAINNET_API_KEY: ${{ secrets.NEXT_PUBLIC_MULTISIG_INDEXER_MAINNET_API_KEY }}
  APTOS_DEVNET_FAUCET_AUTH_TOKEN: ${{ secrets.APTOS_DEVNET_FAUCET_AUTH_TOKEN }}

jobs:
  run-all-checks:
    name: Run All Checks
    runs-on: ubuntu-latest-16-core
    steps:
      - name: Checkout Repo
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955

      - name: Setup pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320

      - name: Setup Node.js 22.x
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: 22.x

      - name: Install safe-chain
        run: curl -fsSL https://github.com/AikidoSec/safe-chain/releases/download/1.4.7/install-safe-chain.sh | sh -s -- --ci

      - name: Install Dependencies
        run: pnpm i

      - name: Run Checks
        run: pnpm check

      - name: Install Playwright
        run: cd apps/web && pnpm exec playwright install

      - name: Run End-to-End Tests
        run: pnpm test:e2e
        shell: bash
